import { ScrollReveal } from "@/components/scroll-reveal"
import { ExternalLink, Search, Gift, Star, MessageCircle, ArrowRight } from "lucide-react"
import Link from "next/link"
import Image from "next/image"

const zopinCapabilities = [
  { icon: Search, title: "Hyperlocal Discovery", description: "Consumers find the right nearby store with real-time inventory and offer awareness." },
  { icon: Gift, title: "AI-Powered Offers", description: "Dynamic, personalized offers generated by AI based on consumer intent and merchant inventory." },
  { icon: Star, title: "Loyalty Engine", description: "Built-in loyalty mechanics that reward repeat customers and build long-term merchant relationships." },
  { icon: MessageCircle, title: "Conversational Commerce", description: "Chat-native buying experience — browse, ask, and purchase without leaving the conversation." },
]

function SectionDivider() {
  return (
    <div className="relative mx-auto w-full max-w-7xl px-6" aria-hidden="true">
      <div className="h-px w-full bg-linear-to-r from-transparent via-primary/20 to-transparent" />
    </div>
  )
}

export default function VenturesPage() {
  return (
    <main className="relative min-h-screen overflow-hidden pt-24">
      <div className="relative z-10">

        {/* Header */}
        <section className="section-shell relative overflow-hidden py-14 md:py-20">
          <div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(ellipse at top, rgba(76,29,149,0.06) 0%, transparent 60%)" }} aria-hidden="true" />
          <div className="relative mx-auto max-w-4xl px-6 text-center">
            <ScrollReveal>
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-neon/20 bg-neon/5 px-4 py-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-neon" />
                <span className="text-xs font-semibold uppercase tracking-widest text-neon">Our Ventures</span>
              </div>
            </ScrollReveal>
            <ScrollReveal delay={0.1}>
              <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl md:text-6xl">
                Products We{" "}
                <span className="bg-clip-text text-transparent bg-gradient-to-r from-primary to-neon">Build</span>
              </h1>
            </ScrollReveal>
            <ScrollReveal delay={0.2}>
              <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">
                Hyperlocalventures incubates and operates AI-native commerce products for local businesses and consumers across India.
              </p>
            </ScrollReveal>
          </div>
        </section>

        <SectionDivider />

        {/* Zopin deep-dive */}
        <section className="section-shell relative overflow-hidden py-14 md:py-20">
          <div className="relative mx-auto max-w-7xl px-6">
            <div className="lg:grid lg:grid-cols-2 lg:gap-16 lg:items-center">
              <div>
                <ScrollReveal>
                  <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5">
                    <span className="text-xs font-bold uppercase tracking-widest text-primary">Live</span>
                  </div>
                </ScrollReveal>
                <ScrollReveal delay={0.1}>
                  <h2 className="text-5xl font-extrabold tracking-tight text-foreground sm:text-6xl">Zopin</h2>
                  <p className="mt-1 text-sm font-semibold uppercase tracking-widest text-neon">by Hyperlocalventures</p>
                </ScrollReveal>
                <ScrollReveal delay={0.2}>
                  <p className="mt-6 text-lg leading-relaxed text-muted-foreground">
                    AI-powered local commerce and customer engagement platform connecting consumers and merchants through hyperlocal discovery, offers, loyalty, and conversational commerce.
                  </p>
                </ScrollReveal>
                <ScrollReveal delay={0.3}>
                  <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
                    Zopin is the first product from Hyperlocalventures — an intelligence layer that sits between local businesses and their communities, making every interaction smarter, faster, and more valuable for both sides.
                  </p>
                </ScrollReveal>
                <ScrollReveal delay={0.4}>
                  <div className="mt-8 flex flex-wrap gap-4">
                    <a
                      href="https://zopin.in"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="group relative flex items-center gap-2 overflow-hidden rounded-full bg-neon px-8 py-3 text-sm font-bold text-white tracking-wide transition-all duration-300"
                    >
                      
                      <span className="relative">Visit Zopin</span>
                      <ExternalLink size={14} className="relative" />
                    </a>
                    <Link href="/contact" className="flex items-center gap-2 rounded-full border border-primary/25 bg-primary/5 px-8 py-3 text-sm font-bold tracking-wide text-primary transition-all duration-300 hover:border-primary/50 hover:bg-primary/10">
                      Partner With Us <ArrowRight size={14} />
                    </Link>
                  </div>
                </ScrollReveal>
              </div>

              {/* Desktop screenshots placeholder */}
              <ScrollReveal delay={0.25}>
                <div className="mt-12 lg:mt-0 space-y-4">
                  {/* Primary desktop screen */}
                  <div className="motion-panel overflow-hidden rounded-2xl border border-border/50 bg-surface/80 shadow-xl">
                    <div className="flex items-center gap-1.5 border-b border-border/40 bg-white/60 px-4 py-2.5">
                      <span className="h-2.5 w-2.5 rounded-full bg-red-400/70" />
                      <span className="h-2.5 w-2.5 rounded-full bg-yellow-400/70" />
                      <span className="h-2.5 w-2.5 rounded-full bg-green-400/70" />
                      <div className="ml-3 flex-1 rounded-md bg-white/80 border border-border/30 px-3 py-0.5 text-[10px] text-muted-foreground">
                        zopin.in/analytics
                      </div>
                    </div>
                    <div className="aspect-video relative overflow-hidden">
                      <Image src="/images/merchantanalytics.png" alt="Zopin Analytics Dashboard" fill className="object-cover" style={{ objectPosition: '22% 0%' }} />
                    </div>
                  </div>
                  {/* Secondary desktop screen */}
                  <div className="motion-panel overflow-hidden rounded-2xl border border-border/50 bg-surface/80 shadow-lg">
                    <div className="flex items-center gap-1.5 border-b border-border/40 bg-white/60 px-4 py-2.5">
                      <span className="h-2.5 w-2.5 rounded-full bg-red-400/70" />
                      <span className="h-2.5 w-2.5 rounded-full bg-yellow-400/70" />
                      <span className="h-2.5 w-2.5 rounded-full bg-green-400/70" />
                      <div className="ml-3 flex-1 rounded-md bg-white/80 border border-border/30 px-3 py-0.5 text-[10px] text-muted-foreground">
                        zopin.in/offers
                      </div>
                    </div>
                    <div className="aspect-video relative overflow-hidden">
                      <Image src="/images/merchantoffers.png" alt="Zopin Offers Dashboard" fill className="object-cover" style={{ objectPosition: '22% 0%' }} />
                    </div>
                  </div>
                </div>
              </ScrollReveal>
            </div>

            {/* Key capabilities */}
            <div className="mt-24">
              <ScrollReveal>
                <h3 className="text-2xl font-bold text-foreground text-center mb-12">Key Capabilities</h3>
              </ScrollReveal>
              <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
                {zopinCapabilities.map((cap, i) => (
                  <ScrollReveal key={cap.title} delay={0.1 * (i + 1)}>
                    <div className="motion-panel group relative h-full overflow-hidden rounded-2xl border border-border/50 bg-surface/80 p-6 backdrop-blur-sm transition-all duration-500 hover:border-neon/40">
                      <div className="absolute inset-0 opacity-0 transition-opacity duration-500 group-hover:opacity-100 pointer-events-none" style={{ background: "radial-gradient(circle at top left, rgba(76,29,149,0.06) 0%, transparent 60%)" }} aria-hidden="true" />
                      <div className="relative">
                        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-neon/10 text-neon group-hover:bg-neon/20 transition-all duration-300">
                          <cap.icon size={22} />
                        </div>
                        <h4 className="mt-5 text-base font-bold text-foreground">{cap.title}</h4>
                        <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{cap.description}</p>
                      </div>
                      <div className="absolute bottom-0 left-6 right-6 h-px bg-gradient-to-r from-transparent via-neon/50 to-transparent opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
                    </div>
                  </ScrollReveal>
                ))}
              </div>
            </div>
          </div>
        </section>

      </div>
    </main>
  )
}
